trigger:
- master

jobs:
  - job: linux
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python39noray:
          python.version: '3.9'
          myenv: ONLY_BUILTINS=1
        Python39withray:
          python.version: '3.9'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install . .[test]
        if [ ! -z "$(myenv)" ]; then
          export $(myenv)
        fi
        if [ -z "$ONLY_BUILTINS" ]; then
          pip install git+https://github.com/acxz/ray.git@py39#egg=ray&subdirectory=python
          pip install .[ray]
        fi
      displayName: 'Install dependencies'

    - script: |
        if [ ! -z "$(myenv)" ]; then
          export $(myenv)
        fi
        make test_coverage
      displayName: 'pytest'

    - script: |
        pip install coveralls
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)

  - job: macos
    pool:
      vmImage: 'macOS-latest'
    strategy:
      matrix:
        Python38noray:
          python.version: '3.8'
          myenv: ONLY_BUILTINS=1

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install . .[test]
        if [ ! -z "$(myenv)" ]; then
          export $(myenv)
        fi
        if [ -z "$ONLY_BUILTINS" ]; then
          pip install .[ray]
        fi
      displayName: 'Install dependencies'

    - script: |
        if [ ! -z "$(myenv)" ]; then
          export $(myenv)
        fi
        make test_coverage
      displayName: 'pytest'

    - script: |
        pip install coveralls
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)
